import os

from dotenv import load_dotenv

load_dotenv()

SERVER_HOST = os.getenv('SERVER_HOST', 'localhost')
SERVER_PORT = os.getenv('SERVER_PORT', 8080)
SERVER_URI = f'ws://{SERVER_HOST}:{SERVER_PORT}/'

SQLALCHEMY_ECHO = os.getenv('SQLALCHEMY_ECHO', False)
SQLALCHEMY_DATABASE_USER = os.getenv('SQLALCHEMY_DATABASE_USER', 'rates')
SQLALCHEMY_DATABASE_PASSWORD = os.getenv('SQLALCHEMY_DATABASE_USER', 'rates')
SQLALCHEMY_DATABASE_NAME = os.getenv('SQLALCHEMY_DATABASE_NAME', 'rates_db')
SQLALCHEMY_DATABASE_HOST = os.getenv('SQLALCHEMY_DATABASE_HOST', 'localhost')
SQLALCHEMY_DATABASE_PORT = os.getenv('SQLALCHEMY_DATABASE_PORT', 5440)

SQLALCHEMY_DATABASE_URI = (
    f'postgresql+psycopg://{SQLALCHEMY_DATABASE_USER}:{SQLALCHEMY_DATABASE_PASSWORD}@'
    f'{SQLALCHEMY_DATABASE_HOST}:{SQLALCHEMY_DATABASE_PORT}/{SQLALCHEMY_DATABASE_NAME}'
)

RABBITMQ_HOST = os.getenv('RABBITMQ_DEFAULT_HOST', 'rabbitmq')
RABBITMQ_PORT = os.getenv('RABBITMQ_DEFAULT_PORT', 5672)
RABBITMQ_USER = os.getenv('RABBITMQ_DEFAULT_USER', 'rabbitmq')
RABBITMQ_PASSWORD = os.getenv('RABBITMQ_DEFAULT_PASS', 'rabbitmq')
RABBITMQ_VHOST = os.getenv('RABBITMQ_DEFAULT_VHOST', '')

CELERY_BROKER_URL = f'amqp://{RABBITMQ_USER}:{RABBITMQ_PASSWORD}@{RABBITMQ_HOST}:{RABBITMQ_PORT}/{RABBITMQ_VHOST}'
