"""delete index from timestamp in Rate table

Revision ID: 1199e8dfde99
Revises: 14d89600402e
Create Date: 2024-01-10 22:58:36.152812

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1199e8dfde99'
down_revision: Union[str, None] = '14d89600402e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rate_timestamp', table_name='rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rate_timestamp', 'rate', ['timestamp'], unique=False)
    # ### end Alembic commands ###
