"""Create Rate and Asset tables

Revision ID: 14d89600402e
Revises: 
Create Date: 2024-01-08 01:35:39.009864

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '14d89600402e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_table('rate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_asset_id'), 'rate', ['asset_id'], unique=False)
    op.create_index(op.f('ix_rate_id'), 'rate', ['id'], unique=False)
    op.create_index(op.f('ix_rate_timestamp'), 'rate', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_timestamp'), table_name='rate')
    op.drop_index(op.f('ix_rate_id'), table_name='rate')
    op.drop_index(op.f('ix_rate_asset_id'), table_name='rate')
    op.drop_table('rate')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
